//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public int DepartmantId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public byte Age { get; set; }
        public short Salary { get; set; }
        public System.DateTime Birth { get; set; }
        public bool Gender { get; set; }
        public bool MarialStatus { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
